// Hand-specified expected outputs; the build checks them against the production engine.
const f=(from,to,...steps)=>({from,to,steps});
const ex=(input,expected)=>({input,expected});
const item=(slug,title,category,problem,limit,fields,examples)=>({slug,title,category,problem,limit,recipe:{fields},examples});
export const catalog=[
  item('csv-quantity-and-unit-price','CSV : quantité et prix unitaire','csv','Convertir les colonnes textuelles d’une ligne CSV en nombres utilisables par une API.','Le prix utilise un point décimal. Aucun calcul de total ni arrondi monétaire.',[f('sku','sku','trim'),f('quantity','quantity','trim','number'),f('unit_price','unit_price','trim','number')],[ex({sku:' ITEM-01 ',quantity:' 2 ',unit_price:'12.50'},{sku:'ITEM-01',quantity:2,unit_price:12.5}),ex({sku:'ITEM-02',quantity:'0',unit_price:'0.00'},{sku:'ITEM-02',quantity:0,unit_price:0})]),
  item('csv-leading-zero-identifiers','CSV : préserver les identifiants à zéros initiaux','csv','Nettoyer des codes article et codes postaux sans les convertir en nombres.','Ne vérifie ni l’existence du code postal ni le format des identifiants.',[f('product_id','product_id','trim'),f('postal_code','postal_code','trim'),f('count','count','trim','number')],[ex({product_id:' 00042 ',postal_code:' 01230 ',count:'2'},{product_id:'00042',postal_code:'01230',count:2}),ex({product_id:'00001',postal_code:'00100',count:'0'},{product_id:'00001',postal_code:'00100',count:0})]),
  item('csv-french-unit-prices','CSV français : prix à virgule','csv','Convertir des montants comme 12,50 et renommer les colonnes pour un consommateur anglophone.','Refuse les séparateurs de milliers, les symboles monétaires et les décimaux avec plusieurs virgules.',[f('reference','sku','trim'),f('prix','unit_price','trim','decimal-comma','number'),f('quantite','quantity','trim','number')],[ex({reference:' A-01 ',prix:' 12,50 ',quantite:'3'},{sku:'A-01',unit_price:12.5,quantity:3}),ex({reference:'B-02',prix:'0,75',quantite:'12'},{sku:'B-02',unit_price:0.75,quantity:12})]),
  item('csv-select-safe-output-fields','CSV : sélectionner les champs de sortie','csv','Produire uniquement les colonnes prévues par le contrat de destination ; écarter les colonnes supplémentaires.','La sélection n’est pas une détection de données sensibles. Choisir explicitement les champs autorisés.',[f('name','name','trim'),f('quantity','quantity','trim','number')],[ex({name:' sample ',quantity:'2',internal_note:'synthetic-note'},{name:'sample',quantity:2}),ex({name:'demo',quantity:'7',unused:'ignored'},{name:'demo',quantity:7})]),
  item('api-snake-case-to-camel-case','API : snake_case vers camelCase','api','Adapter un objet plat à un contrat qui attend des noms camelCase.','Mappage explicite de trois champs ; aucune conversion récursive des noms.',[f('product_id','productId','trim'),f('display_name','displayName','trim'),f('unit_price','unitPrice','trim','number')],[ex({product_id:' 001 ',display_name:' Example ',unit_price:'2.5'},{productId:'001',displayName:'Example',unitPrice:2.5}),ex({product_id:'002',display_name:'Other',unit_price:'0'},{productId:'002',displayName:'Other',unitPrice:0})]),
  item('api-camel-case-to-snake-case','API : camelCase vers snake_case','api','Préparer un objet plat pour une API utilisant snake_case.','Les champs absents sont des erreurs, pas des valeurs par défaut.',[f('itemId','item_id','trim'),f('displayName','display_name','trim'),f('isActive','is_active','trim','lowercase','boolean')],[ex({itemId:' X1 ',displayName:' Demo ',isActive:' TRUE '},{item_id:'X1',display_name:'Demo',is_active:true}),ex({itemId:'X2',displayName:'Other',isActive:'false'},{item_id:'X2',display_name:'Other',is_active:false})]),
  item('api-pagination-parameters','API : typer les paramètres de pagination','api','Transformer page et page_size issus d’un formulaire ou d’une query string.','Convertit seulement les types : ne garantit pas des entiers positifs ni une taille maximale.',[f('page','page','trim','number'),f('page_size','pageSize','trim','number')],[ex({page:' 1 ',page_size:' 25 '},{page:1,pageSize:25}),ex({page:'4',page_size:'100'},{page:4,pageSize:100})]),
  item('api-status-enum-casing','API : uniformiser statut et priorité','api','Éliminer les espaces de bord et les variantes de casse avant une validation enum.','Ne valide pas la liste des statuts autorisés ; utiliser ensuite un schéma enum.',[f('status','status','trim','lowercase'),f('priority','priority','trim','uppercase')],[ex({status:' READY ',priority:' high '},{status:'ready',priority:'HIGH'}),ex({status:'Pending',priority:'low'},{status:'pending',priority:'LOW'})]),
  item('forms-explicit-boolean-flags','Formulaire : booléens textuels explicites','forms','Convertir les chaînes true et false, quelle que soit leur casse, en booléens JSON.','Les valeurs on/off, yes/no, 0/1 et les champs absents sont refusés.',[f('enabled','enabled','trim','lowercase','boolean'),f('archived','archived','trim','lowercase','boolean')],[ex({enabled:' TRUE ',archived:'false'},{enabled:true,archived:false}),ex({enabled:'false',archived:' TRUE '},{enabled:false,archived:true})]),
  item('forms-search-filter','Formulaire : préparer un filtre de recherche','forms','Nettoyer une requête et typer la limite et le drapeau include_archived.','Ne fait pas d’échappement SQL ; le consommateur doit utiliser des requêtes paramétrées.',[f('query','query','trim'),f('limit','limit','trim','number'),f('include_archived','includeArchived','trim','lowercase','boolean')],[ex({query:' sample ',limit:'20',include_archived:' FALSE '},{query:'sample',limit:20,includeArchived:false}),ex({query:' demo ',limit:'5',include_archived:'true'},{query:'demo',limit:5,includeArchived:true})]),
  item('forms-measurement-input','Formulaire : valeur et unité de mesure','forms','Préparer des valeurs textuelles et normaliser la casse d’une unité de mesure.','Ne convertit pas entre unités et n’effectue pas de contrôle de plausibilité physique.',[f('value','value','trim','number'),f('unit','unit','trim','lowercase')],[ex({value:' 12.5 ',unit:' KG '},{value:12.5,unit:'kg'}),ex({value:'0.25',unit:'L'},{value:0.25,unit:'l'})]),
  item('forms-preserve-phone-and-reference','Formulaire : préserver téléphone et référence','forms','Conserver les signes plus et les zéros initiaux tout en nettoyant les espaces de bord.','Ne valide pas de numéro de téléphone et ne reformate pas les espaces internes.',[f('phone','phone','trim'),f('reference','reference','trim')],[ex({phone:' +000 000 000 ',reference:' 0007 '},{phone:'+000 000 000',reference:'0007'}),ex({phone:'000-0000',reference:'A-002'},{phone:'000-0000',reference:'A-002'})]),
  item('inventory-stock-import','Stock : normaliser une ligne d’import','inventory','Préparer un SKU, une quantité disponible et un seuil de réapprovisionnement.','Ne valide pas les stocks négatifs ou fractionnaires ; ne déclenche aucune commande.',[f('sku','sku','trim','uppercase'),f('on_hand','onHand','trim','number'),f('reorder_level','reorderLevel','trim','number')],[ex({sku:' item-01 ',on_hand:'12',reorder_level:'3'},{sku:'ITEM-01',onHand:12,reorderLevel:3}),ex({sku:'item-02',on_hand:'0',reorder_level:'5'},{sku:'ITEM-02',onHand:0,reorderLevel:5})]),
  item('inventory-location-codes','Stock : emplacements et codes de lot','inventory','Uniformiser la casse des emplacements tout en préservant les identifiants de lot.','Aucune validation de l’existence d’un emplacement ; les lots restent des textes.',[f('warehouse','warehouse','trim','uppercase'),f('bin','bin','trim','uppercase'),f('batch','batch','trim')],[ex({warehouse:' wh-a ',bin:' b-02 ',batch:' 00019 '},{warehouse:'WH-A',bin:'B-02',batch:'00019'}),ex({warehouse:'wh-b',bin:'c-01',batch:'Lot-A'},{warehouse:'WH-B',bin:'C-01',batch:'Lot-A'})]),
  item('commerce-currency-and-amount','Commerce : devise et montant décimal','commerce','Normaliser la casse d’un code de devise et convertir un montant à point décimal.','Ne valide pas ISO 4217, ne convertit pas de devise et ne garantit pas une arithmétique monétaire exacte.',[f('currency','currency','trim','uppercase'),f('amount','amount','trim','number')],[ex({currency:' eur ',amount:'12.50'},{currency:'EUR',amount:12.5}),ex({currency:'usd',amount:'0.99'},{currency:'USD',amount:0.99})]),
  item('commerce-tax-rate-input','Commerce : typer un taux fourni séparément','commerce','Convertir un taux textuel sans signe pourcent et conserver son libellé.','19.6 reste 19.6 : aucune division par 100, aucun calcul ni conseil fiscal.',[f('label','label','trim'),f('rate','rate','trim','number')],[ex({label:' example-rate ',rate:'19.6'},{label:'example-rate',rate:19.6}),ex({label:'zero-example',rate:'0'},{label:'zero-example',rate:0})]),
  item('commerce-catalog-availability','Catalogue : disponibilité et prix','commerce','Préparer un enregistrement produit avec identifiant texte, booléen de disponibilité et prix numérique.','Ne déduit pas la disponibilité du stock ; le booléen doit être fourni explicitement.',[f('id','id','trim'),f('available','available','trim','lowercase','boolean'),f('price','price','trim','number')],[ex({id:' 0009 ',available:' TRUE ',price:'9.95'},{id:'0009',available:true,price:9.95}),ex({id:'0010',available:'false',price:'0'},{id:'0010',available:false,price:0})]),
  item('logs-http-status-and-latency','Logs : statut HTTP et latence numériques','logs','Typer un événement de log plat avant agrégation, en conservant le request_id comme texte.','Ne vérifie pas la plage des codes HTTP et ne calcule pas de métrique agrégée.',[f('request_id','requestId','trim'),f('status_code','statusCode','trim','number'),f('duration_ms','durationMs','trim','number')],[ex({request_id:' req-demo ',status_code:'200',duration_ms:'12.5'},{requestId:'req-demo',statusCode:200,durationMs:12.5}),ex({request_id:'req-other',status_code:'404',duration_ms:'0'},{requestId:'req-other',statusCode:404,durationMs:0})]),
  item('logs-level-and-service','Logs : casse cohérente pour niveau et service','logs','Nettoyer les dimensions textuelles utilisées pour regrouper des événements.','Ne valide pas le niveau et ne traite pas les messages de logs libres.',[f('level','level','trim','uppercase'),f('service','service','trim','lowercase')],[ex({level:' warn ',service:' Worker-A '},{level:'WARN',service:'worker-a'}),ex({level:'info',service:'API'},{level:'INFO',service:'api'})]),
  item('metrics-scientific-notation','Métriques : nombres en notation scientifique','metrics','Convertir une valeur et son poids lorsque la source utilise la notation exponentielle.','Magnitude maximale 1e12 ; ne garantit pas une précision décimale arbitraire.',[f('value','value','trim','number'),f('weight','weight','trim','number')],[ex({value:'1.2e3',weight:'2e-2'},{value:1200,weight:0.02}),ex({value:'-5e1',weight:'1E0'},{value:-50,weight:1})]),
  item('metrics-latitude-longitude','Métriques : typer des coordonnées','metrics','Transformer latitude et longitude textuelles en champs numériques nommés.', 'Ne contrôle pas les plages géographiques et ne fait ni géocodage ni appel réseau.',[f('lat','latitude','trim','number'),f('lon','longitude','trim','number')],[ex({lat:' -20.0 ',lon:'57.5'},{latitude:-20,longitude:57.5}),ex({lat:'0',lon:'0'},{latitude:0,longitude:0})]),
  item('config-retries-timeout-and-flag','Configuration : tentatives, délai et activation','config','Typer trois paramètres provenant d’une configuration textuelle.','Ne valide pas les bornes métier et n’exécute pas de tentative réseau.',[f('retries','retries','trim','number'),f('timeout_ms','timeoutMs','trim','number'),f('enabled','enabled','trim','lowercase','boolean')],[ex({retries:'3',timeout_ms:'1500',enabled:'TRUE'},{retries:3,timeoutMs:1500,enabled:true}),ex({retries:'0',timeout_ms:'250',enabled:' false '},{retries:0,timeoutMs:250,enabled:false})]),
  item('config-feature-flag-names','Configuration : noms de fonctionnalités et booléens','config','Nettoyer un nom de fonctionnalité et convertir son état explicite.','La conversion en minuscules n’est adaptée qu’aux systèmes où les noms sont insensibles à la casse.',[f('feature','feature','trim','lowercase'),f('active','active','trim','lowercase','boolean')],[ex({feature:' New_Search ',active:' TRUE '},{feature:'new_search',active:true}),ex({feature:'EXPORT',active:'false'},{feature:'export',active:false})]),
  item('migration-legacy-flat-field-names','Migration : adapter des champs historiques','api','Renommer un ancien contrat plat vers des noms explicites en gardant les identifiants textuels.', 'Mapping limité aux trois champs spécifiés ; pas de migration de base ni de détection automatique.',[f('ref','externalId','trim'),f('qty','quantity','trim','number'),f('desc','description','trim')],[ex({ref:' 00015 ',qty:'4',desc:' Example item '},{externalId:'00015',quantity:4,description:'Example item'}),ex({ref:'B-6',qty:'1',desc:'Other'},{externalId:'B-6',quantity:1,description:'Other'})])
];
export const asContribution=({slug,recipe,examples})=>({slug,recipe,examples,conventions:{catalog:'attractor_v03'}});
