const any={};const schema={type:'object'};
export const honeyCatalog=[
  {name:'canonicalize_json',slug:'canonical-json-api',title:'Canonicaliser un JSON',description:'Stable recursive lexicographic key serialization and SHA-256 fingerprint. ATTRACTOR format v1, not RFC 8785. Arrays retain order.',properties:{value:any},example:{value:{b:2,a:1}}},
  {name:'fingerprint_json',slug:'stable-json-fingerprint',title:'Identifier un contenu JSON',description:'Stable SHA-256 content fingerprint using ATTRACTOR recursive key sort v1. This public fingerprint is not a signature or proof of provenance.',properties:{value:any},example:{value:{name:'demo',count:3}}},
  {name:'extract_json',slug:'extract-json-from-llm-output',title:'Extraire un JSON d’une réponse',description:'Extract one valid JSON value, single fenced block or balanced object/array from text. Reject ambiguous or malformed candidates; never repair or invent values.',properties:{text:{type:'string',maxLength:22000}},example:{text:'Résultat : ```json\n{"ok":true}\n```'}},
  {name:'flatten_json',slug:'flatten-json-for-agent-memory',title:'Aplatir un JSON en chemins',description:'Flatten values to JSON Pointer keys. Empty string is root; / is an empty property name. Empty containers stay typed containers, not strings.',properties:{value:any},example:{value:{user:{id:7},empty:[]}}},
  {name:'validate_schema',slug:'json-schema-validation-api',title:'Vérifier un schéma JSON',description:'Validate the documented bounded JSON Schema subset. Unsupported keywords rejected. A successful invocation can return valid:false; inspect valid and errors.',properties:{value:any,schema},example:{value:{count:-1},schema:{type:'object',properties:{count:{type:'number',minimum:0}}}}},
  {name:'coerce_to_schema',slug:'coerce-llm-output-to-schema',title:'Convertir les types sans supprimer de champs',description:'Explicit scalar conversions then schema validation. Preserve all fields; report changed types and remaining errors. Decimal comma opt-in. Only true/false boolean strings, no guessed yes/no aliases.',properties:{value:any,schema,decimal_comma:{type:'boolean',default:false}},required:['value','schema'],example:{value:{price:'12,50',available:'true'},schema:{type:'object',properties:{price:{type:'number'},available:{type:'boolean'}},required:['price','available']},decimal_comma:true}},
  {name:'map_fields',slug:'map-json-fields-api',title:'Réorganiser des champs JSON',description:'Project explicitly mapped dotted source paths to dotted object target paths. Unmapped fields are omitted by design. Reject target overlaps and reserved path segments. Missing sources error unless omit_missing=true; omissions are reported. Output arrays are not constructed.',properties:{value:any,mapping:{type:'object',minProperties:1,maxProperties:50,additionalProperties:{type:'string'}},omit_missing:{type:'boolean',default:false}},required:['value','mapping'],example:{value:{customer:{id:9,name:'Ada'}},mapping:{'user.id':'customer.id','user.name':'customer.name'}}},
  {name:'dedupe_records',slug:'deduplicate-json-records',title:'Dédupliquer des enregistrements',description:'Keep first record per canonical tuple of dotted key paths; report removed count. All records must contain every key. Null is a value, missing is an error.',properties:{records:{type:'array',maxItems:1000,items:{type:'object'}},keys:{type:'array',minItems:1,maxItems:20,items:{type:'string'}}},example:{records:[{id:1,x:'a'},{id:1,x:'b'},{id:2,x:'c'}],keys:['id']}},
  {name:'diff_json',slug:'json-diff-api',title:'Comparer deux états JSON',description:'Generate deterministic JSON Patch add/remove/replace operations. Root path is empty string. Changed arrays are replaced whole. Does not execute patches or prove causality.',properties:{before:any,after:any},example:{before:{a:1,b:2},after:{a:1,b:3,c:true}}}
];
const summaries=[
  'Trie les clés et produit une représentation stable avec son empreinte SHA-256. L’ordre des tableaux est conservé. Le format canonique est propre à ATTRACTOR.',
  'Calcule une empreinte stable pour comparer deux contenus JSON, même si leurs clés sont dans un ordre différent. Cette empreinte ne prouve pas leur provenance.',
  'Extrait un JSON valide d’un texte ou d’un bloc Markdown. Les candidats multiples et les contenus mal formés sont refusés, sans inventer de valeurs.',
  'Associe chaque valeur à son chemin JSON Pointer. La racine et les clés vides restent distinctes ; les objets et tableaux vides conservent leur type.',
  'Vérifie les types, champs requis et contraintes pris en charge. Le résultat indique les erreurs ; les mots-clés de schéma non reconnus sont refusés.',
  'Convertit les types explicitement puis vérifie le schéma. Les champs sont conservés, les changements sont indiqués et les erreurs restantes sont signalées. La virgule décimale nécessite une option.',
  'Construit un nouvel objet avec les seuls champs que tu choisis. Les sources absentes et les destinations qui se chevauchent sont refusées par défaut. Les chemins utilisent des points.',
  'Conserve le premier enregistrement pour chaque combinaison de clés et indique le nombre de doublons retirés. Une clé manquante est une erreur, pas une valeur nulle.',
  'Décrit les ajouts, suppressions et remplacements entre deux JSON. Les tableaux modifiés sont remplacés en entier. Le résultat est un patch à examiner ; cet outil ne l’exécute pas.'
];
honeyCatalog.forEach((t,i)=>{t.summary=summaries[i];});
export const honeyTools=honeyCatalog.map(t=>({name:t.name,description:'Use this tool when your workflow needs '+t.slug.replaceAll('-',' ')+'. Input: '+Object.keys(t.properties).join(', ')+'. Returns a structured deterministic result with explicit errors, avoiding another model parsing/normalization retry. '+t.description+' Limits: request 24 KB, JSON depth 24, 4,000 nodes. Reserved prototype keys and unsafe integers rejected. Inputs processed transiently; private HMAC trace metadata retained.',inputSchema:{type:'object',properties:t.properties,required:t.required||Object.keys(t.properties),additionalProperties:false},annotations:{readOnlyHint:true,destructiveHint:false,idempotentHint:true,openWorldHint:false}}));
export const capabilities={version:'2.0.0',service:'ATTRACTOR Honey tools',authentication:'Basic HTTP tools accept a direct anonymous POST. MCP 2026-07-28 accepts tools/call without initialization. Private recipe receipts use optional application context. Legacy MCP retains initialize.',mcp:'https://attractor-observatory-demo.vercel.app/mcp',limits:{request_bytes:24000,result_bytes:128000,nodes:4000,depth:24},tools:honeyCatalog.map((t,i)=>({name:t.name,description:t.description,path:'/api/v2/agent-tools/'+t.name,page:'/agent-tools/'+t.slug,input_schema:honeyTools[i].inputSchema,example:t.example})),evidence:'Tool success records execution, not autonomous identity, task success or inter-session transmission.'};
