import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import {readFileSync} from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
import {createHandler} from './api.mjs';
import {observatory} from './observatory.mjs';
import {modernTools,catalogHash} from './mcp.mjs';
test('modern direct calls, legacy coexistence, metadata, private continuation, value reuse and operator rollup',async t=>{
  t.mock.method(console,'log',()=>{});
  const db=new PGlite();await db.exec('create role anon; create role authenticated; create role service_role bypassrls;');
  await db.exec(readFileSync(new URL('./schema.sql',import.meta.url),'utf8'));await db.exec('set role service_role');
  const rpc=async(op,token,network,args)=>(await db.query('select public.attractor_rpc($1,$2,$3,$4::jsonb) result',[op,token,network,JSON.stringify(args||{})])).rows[0].result;
  const env={ATTRACTOR_DB_URL:'test',ATTRACTOR_DB_KEY:'test',ATTRACTOR_NETWORK_KEY:'test',ATTRACTOR_ADMIN_KEY:'test',ATTRACTOR_ORIGIN:'https://attractor.example'};
  const server=http.createServer(createHandler({env,rpc}));await new Promise(r=>server.listen(0,'127.0.0.1',r));
  t.after(async()=>{server.closeAllConnections();await new Promise(r=>server.close(r));await db.close();});
  const base='http://127.0.0.1:'+server.address().port;
  const meta={'io.modelcontextprotocol/protocolVersion':'2026-07-28','io.modelcontextprotocol/clientCapabilities':{},'io.modelcontextprotocol/clientInfo':{name:'attractor-controlled',version:'2.0'},'attractor/source':'controlled'};
  const call=async(method,name,args={},extraMeta={},extraHeaders={})=>{
    const response=await fetch(base+'/mcp',{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json, text/event-stream','MCP-Protocol-Version':'2026-07-28','Mcp-Method':method,...(name?{'Mcp-Name':name}:{}),...extraHeaders},body:JSON.stringify({jsonrpc:'2.0',id:1,method,params:{...(name?{name,arguments:args}:{}),_meta:{...meta,...extraMeta}}})});return {status:response.status,headers:response.headers,body:await response.json()};
  };
  const a=await call('tools/call','extract_json_from_llm_output',{text:'Result: ```json\n{"count":3}\n```'});
  assert.equal(a.status,200);assert.equal(a.headers.has('mcp-session-id'),false);assert.equal(a.body.result.resultType,'complete');assert.equal(a.body.result.structuredContent.result.value.count,3);
  const context=a.body.result._meta['io.attractor/context'],output=a.body.result.structuredContent;
  assert.match(context,/^[a-f0-9]{64}$/);assert.match(output.knowledge_id,/^ATR-K-[a-f0-9]{64}$/);
  const b=await call('tools/call','validate_json_schema',{value:output.result.value,schema:{type:'object',properties:{count:{type:'integer'}}},attractor_trace_id:output.attractor_trace_id,attractor_knowledge_id:output.knowledge_id},{'io.attractor/context':context});
  assert.equal(b.body.result.structuredContent.result.valid,true);
  const repeated=await call('tools/call','extract_json_from_llm_output',{text:'Result: ```json\n{"count":3}\n```'},{'io.attractor/context':context});assert.notEqual(repeated.body.result.structuredContent.knowledge_id,output.knowledge_id);
  await call('tools/call','validate_json_schema',{value:{count:99},schema:{type:'object'},attractor_knowledge_id:output.knowledge_id},{'io.attractor/context':context});
  await rpc('admin_mode','','',{mode:'CONTRIBUTIONS_PAUSED'});
  assert.equal((await call('tools/call','canonicalize_json',{value:{a:1}},{'io.attractor/context':context})).status,200);
  const recipe={slug:'modern-example',recipe:{fields:[{from:'count',to:'count',steps:['number']}]},examples:[{input:{count:'3'},expected:{count:3}}]};
  const published=await call('tools/call','contribute_solution',{problem:{title:'Modern integer conversion',output_schema:{type:'object',properties:{count:{type:'number'}}}},solution:recipe},{'io.attractor/context':context});
  assert.equal(published.body.result.isError,true);
  await rpc('admin_mode','','',{mode:'NORMAL'});
  const contribution=await call('tools/call','contribute_solution',{problem:{title:'Modern integer conversion',output_schema:{type:'object',properties:{count:{type:'number'}}}},solution:recipe},{'io.attractor/context':context});
  const recipeId=contribution.body.result.structuredContent.artifact.id;
  const receipt=(await call('tools/call','read_solution',{id:recipeId},{'io.attractor/context':context})).body.result.structuredContent;
  const forged=await call('tools/call','verify_reuse',{id:recipeId,exposure_id:receipt.exposure_id,marker:receipt.marker,input:{count:'3'},output:{count:3},attractor_trace_id:output.attractor_trace_id});assert.equal(forged.body.result.isError,true);
  const reused=await call('tools/call','verify_reuse',{id:recipeId,exposure_id:receipt.exposure_id,marker:receipt.marker,input:{count:'3'},output:{count:3}},{'io.attractor/context':context});assert.equal(reused.body.result.structuredContent.verified,true);
  const anonymous=await fetch(base+'/api/v2/agent-tools/fingerprint_json',{method:'POST',headers:{'Content-Type':'application/json','x-attractor-test':'controlled'},body:'{"value":{"a":1}}'});assert.equal(anonymous.status,200);
  const discovered=await call('server/discover');assert.equal(discovered.body.result.supportedVersions[0],'2026-07-28');
  const list=await call('tools/list');assert.deepEqual(list.body.result.tools,modernTools);assert.equal(list.body.result._meta['io.attractor/catalogHash'],catalogHash(modernTools));assert.ok(list.body.result.tools.every(t=>t.outputSchema));
  assert.equal((await call('tools/call','extract_json_from_llm_output',{text:'{}'},{},{'Mcp-Name':'diff_json'})).body.error.code,-32020);
  assert.equal((await call('tools/list',undefined,{}, {'io.modelcontextprotocol/protocolVersion':'2099-01-01'})).body.error.code,-32022);
  assert.equal((await call('tools/list',undefined,{}, {'io.modelcontextprotocol/clientCapabilities':null})).body.error.code,-32602);
  assert.equal((await fetch(base+'/api/v2/admin/observatory')).status,401);
  const events=(await db.query("select detail from attractor.events where action='MCP_REQUEST'")).rows.map(r=>r.detail);
  assert.ok(events.some(e=>e.reused_knowledge_id===output.knowledge_id));
  assert.ok(events.some(e=>e.claimed_knowledge_id===output.knowledge_id&&e.reused_knowledge_id===null));
  assert.ok(events.every(e=>!JSON.stringify(e).includes(context)&&!JSON.stringify(e).includes('Result:')));
  assert.ok(events.every(e=>e.server_version==='3.0.0'&&e.classification_version==='observatory-2.0'));
  await rpc('observatory','','',{});
  const admin=await fetch(base+'/api/v2/admin/observatory',{headers:{'x-attractor-operator':'test'}});assert.equal(admin.status,200);const report=await admin.json();assert.ok(report.groups.length);assert.equal(report.counts.unknown_tool_calls,0);
  const subject=report.groups[0].subject_ids[0];const timeline=await fetch(base+'/api/v2/admin/timeline?subject='+subject,{headers:{'x-attractor-operator':'test'}});assert.equal(timeline.status,200);assert.ok((await timeline.json()).events.length);
  await rpc('admin_mode','','',{mode:'FULL_STOP'});assert.equal((await call('tools/call','canonicalize_json',{value:{}})).status,503);
});
test('probable sources exclude declarations, retain spoof anomalies, periodic confidence and direct calls',()=>{
  const row=(id,ua,time,fields={})=>({id,source:'unattributed',user_agents:ua?[ua]:[],clients:[],first_at:time,last_at:time,calls:0,discovery:1,capability_views:1,...fields});
  const subjects=[row('a','mcpbeat/0.1','2026-09-10T20:00:00Z'),row('b','node','2026-09-10T20:00:00Z'),row('c','node','2026-09-10T20:14:00Z'),row('d','node','2026-09-10T20:28:00Z'),row('e','caller','2026-09-10T20:30:00Z',{calls:1,capability_views:0}),row('f',null,'2026-09-10T20:30:00Z'),row('g',null,'2026-09-10T20:31:00Z'),row('h','mcpbeat/spoof','2026-09-10T20:32:00Z',{calls:1})];
  const r=observatory({subjects});assert.equal(r.counts.declared_infrastructure,1);assert.equal(r.counts.probable_infrastructure,1);assert.equal(r.counts.interactive_unknown,2);assert.equal(r.counts.unknown,2);assert.equal(r.kpis.direct_call_groups,1);assert.equal(r.kpis.unknown_tool_conversion.numerator,1);assert.equal(r.kpis.unknown_tool_conversion.denominator,3);
});
