import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import {readFileSync} from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
import {createHandler} from './api.mjs';
import {verifyArtifact,stateShare,findCapability,nativeTools} from './native.mjs';
import {initial,fragment,parseFragment} from './discussion-contract.mjs';

test('discussion draft and server contract reject malformed sources and unlinked critiques',()=>{
  const d=initial(); assert.deepEqual(parseFragment(fragment(d)),d);
  const body={artifact:d.artifact,title:'Discussion test',kind:'json',tags:['civilisation-discussion'],visibility:'public'};
  assert.equal(stateShare(body).artifact.format,'attractor-discussion-v1');
  assert.throws(()=>stateShare({...body,artifact:{...d.artifact,limits:''}}));
  assert.throws(()=>stateShare({...body,artifact:{...d.artifact,type:'critique'}}));
  assert.throws(()=>stateShare({...body,artifact:{...d.artifact,sources:[{title:'unsafe',url:'javascript:alert(1)'}]}}));
  assert.throws(()=>fragment({...d,access_token:'private'}));
  assert.throws(()=>stateShare({...body,artifact:{...d.artifact,unknown:true}}));
});
test('native contracts reject unsupported guarantees and require explicit public writes',()=>{
  assert.throws(()=>stateShare({artifact:{},title:'test',kind:'json',tags:[]}));
  assert.throws(()=>verifyArtifact({artifact:1,constraints:{type:'number',unknownCheck:true}}));
  assert.equal(verifyArtifact({artifact:'throw new Error()',constraints:{type:'string'}}).verification.code_executed,false);
  assert.equal(findCapability({query:'share_state'},nativeTools).capabilities[0].name,'share_state');
  assert.throws(()=>stateShare({artifact:'x'.repeat(12001),visibility:'public',title:'test',kind:'code',tags:[]}));
});
test('HTTP, MCP and A2A handoff: immutable lineage, private receipts, explicit verification, modes and audit',async t=>{
  t.mock.method(console,'log',()=>{});
  const db=new PGlite();await db.exec('create role anon; create role authenticated; create role service_role bypassrls;');
  await db.exec(readFileSync(new URL('./schema.sql',import.meta.url),'utf8'));await db.exec('set role service_role');
  const rpc=async(op,token,network,args)=>(await db.query('select public.attractor_rpc($1,$2,$3,$4::jsonb) result',[op,token,network,JSON.stringify(args||{})])).rows[0].result;
  const env={ATTRACTOR_DB_URL:'test',ATTRACTOR_DB_KEY:'test',ATTRACTOR_NETWORK_KEY:'test',ATTRACTOR_ADMIN_KEY:'test',ATTRACTOR_ORIGIN:'https://attractor.example'};
  const server=http.createServer(createHandler({env,rpc}));await new Promise(r=>server.listen(0,'127.0.0.1',r));
  t.after(async()=>{server.closeAllConnections();await new Promise(r=>server.close(r));await db.close();});
  const base='http://127.0.0.1:'+server.address().port;
  const post=async(path,body,headers={})=>{const r=await fetch(base+path,{method:'POST',headers:{'Content-Type':'application/json','x-attractor-test':'controlled',...headers},body:JSON.stringify(body)});return {status:r.status,body:await r.json(),context:r.headers.get('X-Attractor-Context')};};
  const state={artifact:{count:1},visibility:'public',title:'Native controlled example',kind:'json',tags:['native-test']};
  const a=await post('/api/v3/share_state',state);assert.equal(a.status,200);assert.match(a.body.state.id,/^ATR-S-/);assert.ok(a.context);assert.equal(a.body.state.session_id,undefined);
  const b=await post('/api/v3/retrieve_state',{id:a.body.state.id});assert.equal(b.body.state.artifact.count,1);assert.notEqual(a.context,b.context);
  assert.equal((await post('/api/v3/share_state',{...state,parent_id:a.body.state.id,read_receipt:b.body.read_receipt,artifact:{count:2}},{Authorization:'Bearer '+a.context})).status,409);
  assert.equal((await post('/api/v3/share_state',{...state,parent_id:a.body.state.id,read_receipt:b.body.read_receipt},{Authorization:'Bearer '+b.context})).status,409);
  const derived=await post('/api/v3/share_state',{...state,parent_id:a.body.state.id,read_receipt:b.body.read_receipt,artifact:{count:2}},{Authorization:'Bearer '+b.context});assert.equal(derived.status,200);assert.equal(derived.body.state.parent_id,a.body.state.id);
  const a2a=async(capability,args,context)=>post('/a2a',{jsonrpc:'2.0',id:1,method:'SendMessage',params:{message:{messageId:'controlled-message',role:'ROLE_USER',parts:[{data:{capability,arguments:args}}],...(context?{metadata:{'io.attractor/context':context}}:{})}}},{'A2A-Version':'1.0'});
  const read=await a2a('retrieve_state',{id:derived.body.state.id});assert.equal(read.status,200);assert.ok(read.body.result,JSON.stringify(read.body));
  const message=read.body.result.message,c=message.metadata['io.attractor/context'],artifact=message.parts[0].data;
  assert.equal(message.role,'ROLE_AGENT');assert.notEqual(message.contextId,c);assert.equal(artifact.state.artifact.count,2);
  const args={artifact:artifact.state.artifact,constraints:{type:'object',required:['count'],properties:{count:{type:'integer',minimum:2}},additionalProperties:false},state_id:artifact.state.id,read_receipt:artifact.read_receipt};
  const check=await a2a('verify_artifact',args,c);assert.equal(check.body.result.message.parts[0].data.state_use.verified,true);
  const replay=await a2a('verify_artifact',args,c);assert.equal(replay.body.result.message.parts[0].data.state_use.already_recorded,true);
  assert.equal((await a2a('verify_artifact',{...args,artifact:{count:3}},c)).body.error.code,-32602);
  const search=await post('/api/v3/retrieve_state',{query:'native-test'},{Authorization:'Bearer '+c});assert.equal(search.body.states.length,2);assert.equal(search.body.states[0].artifact,undefined);
  const mcp=await post('/mcp',{jsonrpc:'2.0',id:2,method:'tools/call',params:{name:'verify_artifact',arguments:{artifact:{count:2},constraints:{type:'object'}},_meta:{'io.modelcontextprotocol/protocolVersion':'2026-07-28','io.modelcontextprotocol/clientCapabilities':{},'attractor/source':'controlled','io.attractor/context':c}}},{Accept:'application/json, text/event-stream','MCP-Protocol-Version':'2026-07-28','Mcp-Method':'tools/call','Mcp-Name':'verify_artifact'});
  assert.equal(mcp.body.result.structuredContent.valid,true);
  const events=(await db.query('select action,detail from attractor.events')).rows;
  assert.equal(events.filter(e=>e.action==='STATE_VERIFIED').length,1);assert.equal(events.filter(e=>e.action==='STATE_DERIVED').length,1);
  assert.ok(events.some(e=>e.action==='A2A_REQUEST'&&e.detail.jsonrpc_method==='SendMessage'&&e.detail.tool_name==='verify_artifact'));
  assert.ok(events.every(e=>!JSON.stringify(e.detail).includes(c)&&!JSON.stringify(e.detail).includes('Native controlled example')));
  const stats=await rpc('observatory','','',{});assert.equal(stats.links.filter(l=>l.kind==='state_verified').length,1);assert.equal(stats.subjects.reduce((n,s)=>n+s.states_read,0),2);
  await rpc('admin_mode','','',{mode:'CONTRIBUTIONS_PAUSED'});assert.equal((await post('/api/v3/share_state',state,{Authorization:'Bearer '+c})).status,503);assert.equal((await post('/api/v3/retrieve_state',{id:a.body.state.id},{Authorization:'Bearer '+c})).status,200);
  await rpc('admin_mode','','',{mode:'FULL_STOP'});assert.equal((await a2a('find_capability',{query:'verify'},c)).status,503);
  await db.exec('reset role;set role anon');await assert.rejects(db.query('select * from attractor.shared_states'));await assert.rejects(db.query("select public.attractor_rpc('retrieve_state','','','{}')"));
});
