// Adds, to every page, the Open Graph image generated by src/pages/og/[...route].ts, so a shared link
// shows a card. Uses Starlight's route data middleware, the documented way to extend a page's <head>.
// A French page served under /en/ as a fallback points search engines to the French original.
import {defineRouteMiddleware} from '@astrojs/starlight/route-data';

export const onRequest = defineRouteMiddleware(context => {
  const route = context.locals.starlightRoute;
  // Starlight gives the home page an empty id; the image route names it after its file, "index".
  const image = new URL(`/og/${route.entry.id || 'index'}.png`, context.site).href;
  route.head.push({tag: 'meta', attrs: {property: 'og:image', content: image}});
  route.head.push({tag: 'meta', attrs: {property: 'og:image:width', content: '1200'}});
  route.head.push({tag: 'meta', attrs: {property: 'og:image:height', content: '630'}});
  route.head.push({tag: 'meta', attrs: {name: 'twitter:image', content: image}});
  if (route.isFallback) {
    const original = new URL(context.url.pathname.replace(/^\/en(\/|$)/, '/'), context.site).href;
    for (const entry of route.head) {
      if (entry.tag === 'link' && entry.attrs?.rel === 'canonical') entry.attrs.href = original;
    }
    route.head.push({tag: 'meta', attrs: {name: 'robots', content: 'noindex, follow'}});
  }
});
